package com.sad.programmer.framework.spring.transaction;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * Mock 数据库连接，用于测试事务管理器。
 *
 * <p>不连接真实数据库，只记录 commit/rollback/close 调用状态，
 * 验证事务管理器的生命周期控制是否正确。</p>
 *
 * @author sad-programmer
 * @since 1.0.0
 */
public class MockConnection implements Connection {

    /** 是否已提交。 */
    private boolean committed;

    /** 是否已回滚。 */
    private boolean rolledBack;

    /** 是否已关闭。 */
    private boolean closed;

    /** 自动提交状态。 */
    private boolean autoCommit = true;

    /** 创建时间戳（用于验证同一事务使用同一连接）。 */
    private final long createTime = System.currentTimeMillis();

    @Override
    public void commit() {
        this.committed = true;
    }

    @Override
    public void rollback() {
        this.rolledBack = true;
    }

    @Override
    public void close() {
        this.closed = true;
    }

    @Override
    public void setAutoCommit(boolean autoCommit) {
        this.autoCommit = autoCommit;
    }

    @Override
    public boolean getAutoCommit() {
        return autoCommit;
    }

    @Override
    public boolean isClosed() {
        return closed;
    }

    /**
     * 是否已提交。
     *
     * @return true 表示已提交
     */
    public boolean isCommitted() {
        return committed;
    }

    /**
     * 是否已回滚。
     *
     * @return true 表示已回滚
     */
    public boolean isRolledBack() {
        return rolledBack;
    }

    /**
     * 获取创建时间戳。
     *
     * @return 时间戳
     */
    public long getCreateTime() {
        return createTime;
    }

    // ========== 以下为 Connection 接口的空实现，不影响测试 ==========

    @Override public Statement createStatement() { return null; }
    @Override public PreparedStatement prepareStatement(String sql) { return null; }
    @Override public CallableStatement prepareCall(String sql) { return null; }
    @Override public String nativeSQL(String sql) { return sql; }
    @Override public boolean isValid(int timeout) { return !closed; }
    @Override public void setReadOnly(boolean readOnly) {}
    @Override public boolean isReadOnly() { return false; }
    @Override public void setCatalog(String catalog) {}
    @Override public String getCatalog() { return null; }
    @Override public void setTransactionIsolation(int level) {}
    @Override public int getTransactionIsolation() { return 0; }
    @Override public SQLWarning getWarnings() { return null; }
    @Override public void clearWarnings() {}
    @Override public Statement createStatement(int resultSetType, int resultSetConcurrency) { return null; }
    @Override public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) { return null; }
    @Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) { return null; }
    @Override public Map<String, Class<?>> getTypeMap() { return null; }
    @Override public void setTypeMap(Map<String, Class<?>> map) {}
    @Override public void setHoldability(int holdability) {}
    @Override public int getHoldability() { return 0; }
    @Override public Savepoint setSavepoint() { return null; }
    @Override public Savepoint setSavepoint(String name) { return null; }
    @Override public void rollback(Savepoint savepoint) {}
    @Override public void releaseSavepoint(Savepoint savepoint) {}
    @Override public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) { return null; }
    @Override public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) { return null; }
    @Override public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) { return null; }
    @Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) { return null; }
    @Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes) { return null; }
    @Override public PreparedStatement prepareStatement(String sql, String[] columnNames) { return null; }
    @Override public Clob createClob() { return null; }
    @Override public Blob createBlob() { return null; }
    @Override public NClob createNClob() { return null; }
    @Override public SQLXML createSQLXML() { return null; }
    @Override public void setClientInfo(String name, String value) {}
    @Override public void setClientInfo(Properties properties) {}
    @Override public String getClientInfo(String name) { return null; }
    @Override public Properties getClientInfo() { return null; }
    @Override public Array createArrayOf(String typeName, Object[] elements) { return null; }
    @Override public Struct createStruct(String typeName, Object[] attributes) { return null; }
    @Override public void setSchema(String schema) {}
    @Override public String getSchema() { return null; }
    @Override public void abort(Executor executor) {}
    @Override public void setNetworkTimeout(Executor executor, int milliseconds) {}
    @Override public int getNetworkTimeout() { return 0; }
    @Override public <T> T unwrap(Class<T> iface) { return null; }
    @Override public boolean isWrapperFor(Class<?> iface) { return false; }
    @Override public DatabaseMetaData getMetaData() { return null; }
}
